### ISSUE TITLE
DirectOperate with 8bit cnt and index (UINT8_CNT_UINT8_INDEX) missing?

### ISSUE THREAD

**Issue by sielukm** [dnp3/opendnp3#181]
The outstation that our application has to handle requires to be operated using 0x17 qualifier which I found to be mapped to UINT8_CNT_UINT8_INDEX enum value in .Net Bindings. But IMaster interface provides only methods to operate at UINT16_CNT_UINT16_INDEX. Is it possible to send "DIRECT_OPERATE" request with 8bit values of cnt and index?

**Comment by jadamcrain** [comment]
Hi,

No, we don't support this optimization since even Level 1 subset DNP3 devices are required to support 0x28. I'd support a pull request that optimized this by checking if all the indices are <= 255 and sending the 0x17 variant, but it's not something we do at the moment.

I'd complain to your outstation vendor. Any DNP3 device is required to support 0x28 to be compliant at any level.

-Adam
