### ISSUE TITLE
Master.getStatistics().link returns null when using Java bindings

### ISSUE THREAD

**Issue by josh-audio** [dnp3/opendnp3#268]
Adding the following code in `MasterDemo.java` after `master.enable()` (line 82) causes a `NullReferenceException`:

```java
System.out.println(master.getStatistics().link.numBadMasterBit);
```

The `NullRefererenceException` happens because `master.getStatistics().link` is null. The same issue happens with `master.getStatistics().transport`.

If my understanding is correct, the following C++ code should be equivalent:

```c++
std::cout << master->GetStackStatistics().link.numBadMasterBit << std::endl;
```

This C++ code works as expected.

--

I'm running on Windows 10. I'm building with the MSVC v16.0.461.62831 (2019) x64 toolchain, and my JDK is OpenJDK 8 update 212.

**Comment by jadamcrain** [comment]
Here's the JNI function that does the conversion:

https://github.com/automatak/dnp3/blob/2.0.x/java/cpp/adapters/Conversions.cpp#L22

I'll look into it during this release cycle.

**Comment by emgre** [comment]
Thanks for the bug report. The issue was caused by a reference that was deleted in the native code.

**Comment by Zannith** [comment]
Not sure if I should make another bug for this, but this same issue will pop up in `com_automatak_dnp3_impl_ChannelImpl.cpp`. Also as an effect of the test for this fix the maven build will fail because it is the only test which makes use of the dll and the java.library.path is not set for the maven-surefire-plugin. What I did to make it work for mine was add the argLine to the plugin configuration. Not sure if there is a more elegant way to set this?

```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>${surefire-plugin.version}</version>
<configuration>
 <argLine>-Djava.library.path=C:\PathToRepo\build\Release</argLine>
 <includes>
   <include>**/*.class</include>
 </includes>
 <reportFormat>brief</reportFormat>
 <useFile>false</useFile>
</configuration>
```

**Comment by emgre** [comment]
You're absolutely right about the `ChannelImpl`, I forgot it. Thanks!

As for the lib path, I'm not super comfortable in hardcoding a path in the POM. I took for granted that the `java.library.path` was properly set when we run the unit tests. Personally, I set it in the launch configuration of IntelliJ. I'll see with Adam what he thinks is best.

There is another test that uses the DLL/so (`DNP3ManagerIntegrationTest`), but it was ignored. I removed the `@Ignore`, because it makes sense to run it.
