### ISSUE TITLE
Class 2/3 scans not working

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#291]
From a user:

"I have found the problem preparing a summary of my code in a simple class to show you an example. But anyway, only works in version 2.2.0. If you execute the outstation example of library code "https://github.com/dnp3/opendnp3/tree/2.0.x/dotnet/examples/outstation" with version 2.3.0, scan class from master only works for class0 and class1, not for class2 or class3."

**Comment by emgre** [comment]
I confirm the issue with the C# bindings on 2.3.1. The `EventConfig::clazz` is just never set, so it always defaults itself to `PointClass::Class1`. Looking at 2.2.0, I doubt it ever worked properly. Fix is in progress.

**This bug is present only if you use the C# bindings.** If you use the C++ API or the Java bindings, it works properly.

**Comment by emgre** [comment]
Fix is available in https://github.com/dnp3/opendnp3/commit/3efacce27278bbcc15e8b128c26db2a182281846.
