### ISSUE TITLE
Send APDU as a single TCP fragment when possible

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#34]
Currently, APDU's are chunked into TPDUs, which are then transmitted individually.  Due to Nagle's algorithm, the first TPDU is transmitted in one fragment and the rest are transmitted in a second fragment.  If all TPDU's were written to the TCP socket at the same time, they could be grouped into one fragment, thus reducing the overall number of packets required by 50%.

**Comment by jadamcrain** [comment]
Thanks for filing.  I'm just going to put a note in her to remind myself that's it's not because of Nagle's algorithm.  Nagle's holds packets for a time only when there are already outstanding frames.  The first frame is always sent instantly.  The issue happens regardless of whether Nagle's is on or off, so it really has nothing to do with it.

This will require some modifications to the interface between the Transport and Link Layers but is quite doable.

**Comment by jadamcrain** [comment]
complete in 2.0.x
