### ISSUE TITLE
Multiple connections on TCP port

### ISSUE THREAD

**Issue by jacob-conford** [dnp3/opendnp3#343]
It would be nice to accept multiple connections on the same TCP port.  For instance, I have 4 master stations expecting to poll an outstation at the same IP+port.  You could specify the maximum amount of stations attempting to connect on that IP+port, then use the existing ServerAcceptMode parameter to specify what to do if that maximum is exceeded.

**Comment by jadamcrain** [comment]
@jacob-conford DNP3 itself makes this harder than it might first appear. The problem is that the outstation side of DNP3 is stateful, and buffers events for a particular DNP3 master, even when that master is not connected.

The only way to do this in practice is to pre-configure the outstation with a list of IP addresses of masters which are allowed to connect, and then use the connecting IP to associated the new connection with the correct pre-allocated application session.

I've toyed with the idea of implementing this in the past, but since it's quite acceptable for most users to just spin up multiple ports, there's never been a strong push/driver to add it.

If a commercial user sponsored this feature, I would do the work, but with all the other things we have on the list ATM, I don't think it's something I would spend limited volunteer time on at this juncture.
