### ISSUE TITLE
How to Start In Docker Container

### ISSUE THREAD

**Issue by abdulhannansheikh** [dnp3/opendnp3#428]
Hi, I have successfully created two docker containers one for master and other for outstation with the help of docker images. Can anyone guide me how we can test master and outstation. As at the moment I am stuck in testing. when I hit the ENTRY point in master container  

```
> /usr/local/bin/master-demo outstation1
> ms(1626837653409) INFO    manager - Starting thread (0)
> channel state change: OPENING
> Enter a command
> x - exits program
> a - performs and ad-hoc range scan
> i - integrity demand scan
> e - exception demand scan
> d - diable unsolcited
> r - cold restart
> c - send crob
>  and it prints tcpclient- Error connecting
```

and on outstation container I am getting this screen

```
> #  /usr/local/bin/outstation-demo
> ms(1626837757192) INFO    manager - Starting thread (0)
> channel state change: OPENING
> ms(1626837757194) WARN    server - Address already in use
> Enter one or more measurement changes then press <enter>
> c = counter, b = binary, d = doublebit, a = analog, 'quit' = exit.
```

Can anyone please guide me how to proceed further from this point
Thanks

**Comment by emgre** [comment]
Your question is a bit vague, but you might have to change the IP/port in order to make them communicate properly. From your logs, your server cannot bind to the port because it is already used. Check that you don't have a zombie process that binded on your port (by default 20000).

Docker also has multiple network configuration. I can't help you any further, but you can read more about it here: https://docs.docker.com/network/
