### ISSUE TITLE
Remote endpoint address should be re-resolved before each async_connect() attempt

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#46]
Currently, in both the 1.1.x and 2.0.x branches, the mRemoteEndpoint.address is resolved once, in the constructor:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/asiopal/src/PhysicalLayerAsyncTCPClient.cpp#L53

The problem is that if a DNS label is provided instead of a static IP address, the DNS label can resolve to different things over time.  To accommodate for this, it would be preferable to re-resolve the address before each mSocket.async_connect() attempt:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/asiopal/src/PhysicalLayerAsyncTCPClient.cpp#L59

A similar thing should be done for the corresponding TCP Server sockets.  (While unusual to use a DNS name for a server socket, it is not impossible.)

**Comment by jadamcrain** [comment]
That's because this repo doesn't have DNS resolution at all.  The old DNS resolution used a blocking synchronous imlementation that created an additional IOService:

https://github.com/gec/dnp3/blob/master/src/opendnp3/APL/PhysicalLayerAsyncBaseTCP.cpp#L98

I deleted it in the fork, but forgot to re-implement it properly using async resoluton. It needs to be implemented this way:

http://stackoverflow.com/questions/4678903/async-resolve-with-boost-asio

I'll create a ticket for this feature where we can comment on how this feature needs to work.

**Comment by jadamcrain** [comment]
New feature ticket open here for comment:

https://github.com/automatak/dnp3/issues/47
